name: Check Version

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Get PR version
        id: pr_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Checkout main code
        uses: actions/checkout@v2

      - name: Get main version
        id: main_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Compare versions
        run: |
          if [ "${{ steps.pr_version.outputs.version }}" = "${{ steps.main_version.outputs.version }}" ]; then
            echo "Version in package.json must be different than the main branch"
            exit 1
          fi